apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 10m
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      version: ">=3.0.0"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      interval: 1h
  values:
    engines:
      replicated:
        mayastor:
          enabled: false
      legacy:
        enabled: false
