apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m

  valuesFrom:
    - kind: Secret
      name: authentik-credentials
      valuesKey: secret-key
      targetPath: authentik.secret-key

    - kind: Secret
      name: authentik-credentials
      valuesKey: postgres-password
      targetPath: authentik.postgresql.postgresql-password

  values:
    authentik:
      secret_key: ""
      error_reporting:
        enalbed: true
      postgresql:
        password: ""
    
    server:
      ingress:
        ingressClassName: traefik
        enabled: true
        hosts:
          - authentik1.lab42.me
    
    postgresql:
      enabled: true
      auth:
        password: ""
